{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mychatbot.serviceAccountName" . }}
  labels:
    {{- include "mychatbot.labels" . | nindent 4 }}
{{- end }}
